### ISSUE TITLE
Crash with Aurora's Decorations

### ISSUE THREAD

**Issue by Alkiasan** [NathanPB/DeepMobLearning-fabric#148]
Aurora's Decorations and Deep Mob Learning: Refabricated seem to crash upon startup on 1.19.2 of Quilt, see logs below:

https://mclo.gs/zLo3Ha0

Hopefully this is fixable

**Comment by RemagOfficial** [comment]
have you tested on fabric, it could be a quilt incompatibility

**Comment by Alkiasan** [comment]
Aurora's Decorations is not available on Fabric sadly

**Comment by RemagOfficial** [comment]
well DMLR is fabric only as far as I know

**Comment by Alkiasan** [comment]
Quilt (should(?)) be able to run any fabric mod from what I know, unless i'm mistaken? I'll take this to the quilt discord and ask em

**Comment by Alkiasan** [comment]
Alright, after some conversation the issue has been narrowed down to an incompatibility with mods using QSL, DeepMobLearning has been added to the Quilt known incompatibilities megathread here: https://forum.quiltmc.org/t/mod-incompatibility-megathread/261 so hopefully the developer shouldn't be pestered too much about it. I'll leave this issue open for now in hopes that compatibility may be implemented in the future, thanks!

**Comment by Luligabi1** [comment]
Hello, sorry for the delayed answer; This is very likely a duplicate of #122; the bug is fixed on 1.20 onwards, but I won't have the time to backport the fix for 1.19 :/
