### ISSUE TITLE
Crash 1.20.1

### ISSUE THREAD

**Issue by Mysterious-Wrangler** [NathanPB/DeepMobLearning-fabric#150]
Crash when opening the deep mob learner

Minecraft 1.20.1
Fabric 0.15.1
Mod 0.5.15-BETA

[crash-2023-12-27_20.15.08-server.txt](https://github.com/CafeteriaGuild/DeepMobLearning-Refabricated/files/13783006/crash-2023-12-27_20.15.08-server.txt)

**Comment by Luligabi1** [comment]
Hi,

I couldn't reproduce the glitch, but found something that might fix it for you. Can you test [this version](https://www.mediafire.com/file/zlro5bt9mnd9pmd/deepmoblearning-refabricated-0.5.15-BETA+1.20.1-bug150.jar/file) and tell me if it prevents the crash? Thanks.

**Comment by Mysterious-Wrangler** [comment]
> Hi,
> 
> I couldn't reproduce the glitch, but found something that might fix it for you. Can you test [this version](https://www.mediafire.com/file/zlro5bt9mnd9pmd/deepmoblearning-refabricated-0.5.15-BETA+1.20.1-bug150.jar/file) and tell me if it prevents the crash? Thanks.

Hi, no its still crashing the server when i use it. Just in case something has changed here is the crash log from the version you sent me.
[crash-2023-12-28_16.36.47-server.txt](https://github.com/CafeteriaGuild/DeepMobLearning-Refabricated/files/13790050/crash-2023-12-28_16.36.47-server.txt)

**Comment by Luligabi1** [comment]
oops, didn't see this was a server crash. I did some more changes and tested on a server, no crashes for me, attach the full log file if this doesn't work either
https://www.mediafire.com/file/mdhi0g2tcddtxl9/150-attempt2-deepmoblearning-refabricated-0.5.15-BETA+1.20.1.jar/file

**Comment by Mysterious-Wrangler** [comment]
> oops, didn't see this was a server crash. I did some more changes and tested on a server, no crashes for me, attach the full log file if this doesn't work either https://www.mediafire.com/file/mdhi0g2tcddtxl9/150-attempt2-deepmoblearning-refabricated-0.5.15-BETA+1.20.1.jar/file

Still crashing, here is the log file: 
[2023-12-28-5.log](https://github.com/CafeteriaGuild/DeepMobLearning-Refabricated/files/13790681/2023-12-28-5.log)

**Comment by Luligabi1** [comment]
Alright, seems this is [a LibGUI issue that was caused by Fabric Loader 0.15.0 and higher](https://github.com/CottonMC/LibGui/commit/cdf7f58331a1c1123043361414e872be93e01ea0). I'll release a version that requires Fabric Loader 0.14.x, you can just downgrade it on your server and your current DML file will work fine.

**Comment by Mysterious-Wrangler** [comment]
> Alright, seems this is [a LibGUI issue that was caused by Fabric Loader 0.15.0 and higher](https://github.com/CottonMC/LibGui/commit/cdf7f58331a1c1123043361414e872be93e01ea0). I'll release a version that requires Fabric Loader 0.14.x, you can just downgrade it on your server and your current DML file will work fine.

I see. Well the problem with downgrading is some of the mods i have require 0.15+ of fabric loader. Will deep mob learning eventually come to 0.15.1? Thanks for taking the time to figure this out.

**Comment by Luligabi1** [comment]
> > Alright, seems this is [a LibGUI issue that was caused by Fabric Loader 0.15.0 and higher](https://github.com/CottonMC/LibGui/commit/cdf7f58331a1c1123043361414e872be93e01ea0). I'll release a version that requires Fabric Loader 0.14.x, you can just downgrade it on your server and your current DML file will work fine.
> 
> I see. Well the problem with downgrading is some of the mods i have require 0.15+ of fabric loader. Will deep mob learning eventually come to 0.15.1? Thanks for taking the time to figure this out.

I'll try to have LibGUI's developer release a backport for 1.20.1 that I can use. If it does happen, you won't have to downgrade loader. I'll keep you updated 😉

**Comment by Mysterious-Wrangler** [comment]
> > > Alright, seems this is [a LibGUI issue that was caused by Fabric Loader 0.15.0 and higher](https://github.com/CottonMC/LibGui/commit/cdf7f58331a1c1123043361414e872be93e01ea0). I'll release a version that requires Fabric Loader 0.14.x, you can just downgrade it on your server and your current DML file will work fine.
> > 
> > 
> > I see. Well the problem with downgrading is some of the mods i have require 0.15+ of fabric loader. Will deep mob learning eventually come to 0.15.1? Thanks for taking the time to figure this out.
> 
> I'll try to have LibGUI's developer release a backport for 1.20.1 that I can use. If it does happen, you won't have to downgrade loader. I'll keep you updated 😉

Thank you very much :)

**Comment by Luligabi1** [comment]
Hi @Mysterious-Wrangler, LibGUI's developer has released a fix for the issue, version `0.5.16-BETA+1.20.1` is already out on Modrinth and should be in a few minutes on CurseForge. Thanks for reporting and your patience 🙂

**Comment by Mysterious-Wrangler** [comment]
Thank you, its working now!
